config/routes.rb
Garitas::Application.routes.draw do
  root to: "garitas#index"
  resources :cities do
    resources :ports
  end
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  attr_accessible :alert_time, :user_id
  belongs_to :user
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country_code, :latitude, :longitude, :name, :state, :ports_attributes
  has_many :ports, dependent: :destroy
  accepts_nested_attributes_for :ports
  validates :country_code, :latitude, :longitude, :name, :state, presence: true
end

app/models/port.rb
class Port < ActiveRecord::Base
  attr_accessible :city_id, :port_number, :title
  belongs_to :city
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :phone, :twitter
  has_many :alerts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  respond_to :html, :json
  def index
    @cities = City.all
    respond_with(@cities) do |format|
      format.html
      format.json { render json: @cities }
    end
  end

  def new
    @city = City.new
    @city.ports.build
  end

  def create
    @city = City.new(params[:city])
    if @city.save
      flash[:notice] = "Ciudad agregada correctamente."
      redirect_to "index"
    else
      flash.now.alert = "Hubo un problema al agregar la ciudad, porfavor intente nuevamente."
      render "new"
    end
  end
  
  def show
    @city = City.find(params[:id])
  end
  
  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update_attributes(params[:city])
      flash[:notice] = "Ciudad actualizada correctamente."
      redirect_to root_path
    else
      flash.now.alert = "Hubo un problema al actualizar la ciudad."
      render "edit"
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to cities_path
  end
end

app/controllers/garitas_controller.rb
require 'borderline'

class GaritasController < ApplicationController
  def index
    #Fetch user location
    data = BorderLine::Geocode.fetch_location "201.166.59.175"
    geoip = data[0].data
    
    #Get all border cities
    cities = City.all
    
    #Determine closest border cities from user
    closest_city = BorderLine::Geocode.get_closest_cities_from_user cities, geoip
    if closest_city
      @found_city = true
      port_string = ""
      
      #Get city's ports
      ports = closest_city.ports
      
      #Put the request URL together with port number
      ports.each do |port|
        port_string += port.port_number+","
      end
      
      #Request port data based on the closest city
      xml = BorderLine::Client.fetch_borders "http://apps.cbp.gov/bwt/customize_rss.asp?portList=#{port_string}&lane=all&action=rss&f=html"
      
      #Parse the returned XML
      ports_data = BorderLine::Client.parse_xml xml
      raise ports_data.inspect
    else
      @found_city = false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/garitas_helper.rb
module GaritasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<header>
	<h1>Listado de ciudades fronterizas</h1>
</header>

<div id="data-table">
	<table>
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Latitud</th>
				<th>Longitud</th>
				<th>Codigo de Pais</th>
				<th>Estado</th>
				<th>Numero de puertos</th>
			</tr>
		</thead>
		<tbody>
			<% @cities.each do |city| %>
			<tr>
				<td><%= city.name%></td>
				<td><%= city.latitude %></td>
				<td><%= city.longitude %></td>
				<td><%= city.country_code %></td>
				<td><%= city.state %></td>
				<td><%= city.ports.count %></td>
				<td><%= link_to "Ver puertos", city_ports_path(city) %></td>
				<td><%= link_to "Editar", edit_city_path(city) %></td>
				<td><%= link_to "Eliminar", city, confirm: "Esta seguro?", method: :delete %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/cities/new.html.erb
<h1>Agregar nueva ciudad</h1>

<%= form_for @city do |f| %>
<% if @city.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@city.errors.count, "error") %> han prohibido registrar esta ciudad:</h2>

	<ul>
		<% @city.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div id="input-name">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div id="input-latitude">
	<%= f.label :latitude, "Latitud" %>
	<%= f.text_field :latitude %>
</div>
<div id="input-longitude">
	<%= f.label :latitude, "Longitud" %>
	<%= f.text_field :longitude %>
</div>
<div id="input-country-code">
	<%= f.label :country_code, "Codigo de pais" %>
	<%= f.text_field :country_code %>
</div>
<div id="input-state">
	<%= f.label :state, "Estado" %>
	<%= f.text_field :state %>
</div>
<div id="nested-fields-for-port">
	<%= f.fields_for :ports do |p| %>
	<div id="input-port-title">
		<%= p.label :title, "Nombre del puerto" %>
		<%= p.text_field :title %>
	</div>
	<div id="input-port-number">
		<%= p.label :port_number, "Numero de puerto" %>
		<%= p.text_field :port_number %>
	</div>
	<% end %>
</div>
<div id="nested-fields-for-port">
	<%= f.fields_for :ports do |p| %>
	<div id="input-port-title">
		<%= p.label :title, "Nombre del puerto" %>
		<%= p.text_field :title %>
	</div>
	<div id="input-port-number">
		<%= p.label :port_number, "Numero de puerto" %>
		<%= p.text_field :port_number %>
	</div>
	<% end %>
</div>
<div id="submit">
	<%= f.submit "Guardar" %>
</div>
<% end %>

app/views/cities/show.html.erb
<h1>Datos para:<%= @city.name %></h1>

<div id="city-data">
	<ul>
		<li><%= @city.name %></li>
		<li><%= @city.latitude %></li>
		<li><%= @city.longitude %></li>
		<li><%= @city.country_code %></li>
		<li><%= @city.state %></li>
	</ul>
	<div id="city-ports">
		<ul>
		<% @city.ports.each do |port| %>
			<li><%= port.title %></li>
			<li><%= port.port_number %></li>
		<% end %>
		</ul>
	</div>
</div>

app/views/garitas/index.html.erb
<h1>Garitas#index</h1>
<p>Find me in app/views/garitas/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garitas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>